In [2]:
import pandas as pd
import numpy as np

# 4. Gradient Descent

## Single input/weight

In [9]:
def gradient_descent(input,initial_weight,goal_pred,max_iter=50,thresh = 0.0000001,verbose=True):
    curr_weight = initial_weight
    
    for iter_num in range(max_iter):
        pred = input * curr_weight
        error = (pred - goal_pred) ** 2
        print(f'Error: {error}  Prediction: {pred}')
        if error < thresh:
            break
        else:
            delta = pred - goal_pred
            weight_delta = delta * input
            curr_weight = curr_weight - weight_delta
    
    return pred

In [10]:
pred = gradient_descent(input=0.5,initial_weight=0.5,goal_pred=0.8)

Error: 0.30250000000000005  Prediction: 0.25
Error: 0.17015625000000004  Prediction: 0.3875
Error: 0.095712890625  Prediction: 0.49062500000000003
Error: 0.05383850097656251  Prediction: 0.56796875
Error: 0.03028415679931642  Prediction: 0.6259765625
Error: 0.0170348381996155  Prediction: 0.669482421875
Error: 0.00958209648728372  Prediction: 0.70211181640625
Error: 0.005389929274097089  Prediction: 0.7265838623046875
Error: 0.0030318352166796153  Prediction: 0.7449378967285156
Error: 0.0017054073093822882  Prediction: 0.7587034225463867
Error: 0.0009592916115275371  Prediction: 0.76902756690979
Error: 0.0005396015314842384  Prediction: 0.7767706751823426
Error: 0.000303525861459885  Prediction: 0.7825780063867569
Error: 0.00017073329707118678  Prediction: 0.7869335047900676
Error: 9.603747960254256e-05  Prediction: 0.7902001285925507
Error: 5.402108227642978e-05  Prediction: 0.7926500964444131
Error: 3.038685878049206e-05  Prediction: 0.7944875723333098
Error: 1.7092608064027242e-05  

In [11]:
def gradient_descent(input,initial_weight,goal_pred,alpha=0.1,max_iter=50,thresh = 0.0000001,verbose=True):
    curr_weight = initial_weight
    
    for iter_num in range(max_iter):
        pred = input * curr_weight
        error = (pred - goal_pred) ** 2
        print(f'Error: {error}  Prediction: {pred}')
        if error < thresh:
            break
        else:
            delta = pred - goal_pred
            weight_delta = delta * input
            curr_weight = curr_weight - (alpha * weight_delta)
    
    return pred

In [12]:
pred = gradient_descent(input=0.5,initial_weight=0.5,goal_pred=0.8,alpha=0.1)

Error: 0.30250000000000005  Prediction: 0.25
Error: 0.2875640625000001  Prediction: 0.26375
Error: 0.27336558691406254  Prediction: 0.27715625
Error: 0.2598681610601807  Prediction: 0.29022734375
Error: 0.2470371706078343  Prediction: 0.30297166015625
Error: 0.23483971030907247  Prediction: 0.31539736865234375
Error: 0.22324449961256201  Prediction: 0.32751243443603517
Error: 0.21222180244419178  Prediction: 0.33932462357513427
Error: 0.20174335094850981  Prediction: 0.3508415079857559
Error: 0.19178227299542716  Prediction: 0.362070470286112
Error: 0.18231302326627793  Prediction: 0.3730187085289592
Error: 0.1733113177425055  Prediction: 0.3836932408157352
Error: 0.1647540714289693  Prediction: 0.3941009097953418
Error: 0.15661933915216394  Prediction: 0.40424838705045824
Error: 0.14888625928152585  Prediction: 0.4141421773741968
Error: 0.1415350002295005  Prediction: 0.4237886229398419
Error: 0.13454670959316892  Prediction: 0.43319390736634583
Error: 0.1279034658070062  Prediction: 

# 5. generalizing gradient descent

## Multiple Inputs/Weights

In [14]:
def neural_network(input,weights):
    out = np.sum(input*weights)
    return out

In [15]:
toes = np.array([8.5,9.5,9.9,9.0])
wlrec = np.array([0.65,0.8,0.8,0.9])
nfans = np.array([1.2,1.3,0.5,1.0])

In [21]:
input_arr = np.array([toes,wlrec,nfans]).T

In [35]:
weights = np.array([0.1,0.2,-.1])

In [24]:
win_loss_binary = np.array([1,1,0,1]).T

In [68]:
def grad_desc_multi_weight(inputs,initial_weights,goal_pred,alpha=0.1,max_iter=50,thresh=0.00001,verbose=True):
    curr_weights = initial_weights
    
    for itern_num in range(max_iter):
        pred = np.sum(inputs*curr_weights)
        error = (pred - goal_pred) ** 2
        delta = pred - goal_pred
        weight_deltas = delta*inputs
        curr_weights = curr_weights - (alpha*weight_deltas)
        if verbose:
            print(f'Error: {error}')
            print(f'Delta: {delta}')
            print(f'weight_deltas: {weight_deltas}')
            print(f'weights: {initial_weights}')
            print(f'curr_weights: {curr_weights}')
      
    return pred

In [69]:
input_arr[0,:]

array([8.5 , 0.65, 1.2 ])

In [70]:
weights

array([ 0.1,  0.2, -0.1])

In [71]:
np.sum(input_arr[0,:]*weights)

0.8600000000000001

In [76]:
pred = grad_desc_multi_weight(input_arr[0,:],weights,win_loss_binary[0],alpha=0.01,verbose=True)

Error: 0.01959999999999997
Delta: -0.1399999999999999
weight_deltas: [-1.19  -0.091 -0.168]
weights: [ 0.1  0.2 -0.1]
curr_weights: [ 0.1119   0.20091 -0.09832]
Error: 0.0013135188062500048
Delta: -0.036242500000000066
weight_deltas: [-0.30806125 -0.02355763 -0.043491  ]
weights: [ 0.1  0.2 -0.1]
curr_weights: [ 0.11498061  0.20114558 -0.09788509]
Error: 8.802712522307997e-05
Delta: -0.009382277187499843
weight_deltas: [-0.07974936 -0.00609848 -0.01125873]
weights: [ 0.1  0.2 -0.1]
curr_weights: [ 0.11577811  0.20120656 -0.0977725 ]
Error: 5.899249206154892e-06
Delta: -0.0024288370069139864
weight_deltas: [-0.02064511 -0.00157874 -0.0029146 ]
weights: [ 0.1  0.2 -0.1]
curr_weights: [ 0.11598456  0.20122235 -0.09774336]
Error: 3.953456517877471e-07
Delta: -0.0006287651801648586
weight_deltas: [-0.0053445  -0.0004087  -0.00075452]
weights: [ 0.1  0.2 -0.1]
curr_weights: [ 0.116038    0.20122644 -0.09773581]
Error: 2.6494589213863218e-08
Delta: -0.0001627715860150758
weight_deltas: [-0.00

In [75]:
pred

1.0

## Multiple outputs single input

In [3]:
weights = np.array([0.3,0.2,0.9])
wlrec = np.array([0.65,1.0,1.0,0.9])
hurt = np.array([0.1,0.0,0.0,0.1])
win = np.array([1.0,1.0,0.0,1.0])
sad = np.array([0.1,0.0,0.1,0.2])

In [5]:
goal_preds = np.array([hurt,win,sad]).T

In [6]:
goal_preds[0,:]

array([0.1, 1. , 0.1])

In [13]:
def grad_desc_mult_outputs(inputs,initial_weights,goal_preds,alpha=0.1,max_iter=50,thresh=0.00001,verbose=True):
    curr_weights = initial_weights
    
    for itern_num in range(max_iter):
        preds = inputs*curr_weights
        error = (preds - goal_preds) ** 2
        delta = preds - goal_preds
        weight_deltas = deltas*inputs
        curr_weights = curr_weights - (alpha*weight_deltas)
        if verbose:
            print(f'Error: {errors}')
            print(f'Delta: {deltas}')
            print(f'weight_deltas: {weight_deltas}')
            print(f'weights: {initial_weights}')
            print(f'curr_weights: {curr_weights}')
    return preds

In [12]:
preds

array([0.1, 1. , 0.1])

In [11]:
preds = grad_desc_mult_outputs(wlrec[0],weights,goal_preds[0,:],alpha=0.1,max_iter=500,verbose=False)

In [18]:
weights = np.array([[0.1,0.1,-0.3],[0.1,0.2,0.0],[0.0,1.3,0.1]])
toes = np.array([8.5,9.5,9.9,9.0])
wlrec = np.array([0.65,0.8,0.8,0.9])
nfans = np.array([1.2,1.3,0.5,1.0])
hurt = np.array([0.1,0.0,0.0,0.1])
win = np.array([1.0,1.0,0.0,1.0])
sad = np.array([0.1,0.0,0.1,0.2])

In [54]:
transposed_weights = weights.T

In [55]:
inputs = np.array([toes,wlrec,nfans]).T

In [21]:
inputs

array([[8.5 , 0.65, 1.2 ],
       [9.5 , 0.8 , 1.3 ],
       [9.9 , 0.8 , 0.5 ],
       [9.  , 0.9 , 1.  ]])

In [23]:
goal_preds = np.array([hurt,win,sad]).T

In [91]:
def grad_desc_generalized(inputs,initial_weights,goal_preds,alpha=0.1,max_iter=5000,thresh=0.0000001,verbose=True):
    '''function to perform gradient descent with an arbitrary number of inputs,outputs, and weights for a fully connected
    neural network
    inputs (np.array): inputs to model
    initial_weights (np.array): initial weights, could be randomized
    goal_preds (np.array): ground truth output data that will be used for training model
    alpha (float between 0 and 1): controls learning rate(amount weights adjust each iteration), small 
    will make convergence slower, large values will possibly make model diverge
    max_iter (int): max iterations for training
    thresh (float): error threshold to stop training
    verbose (bool): to print diagnostic text or not 
    '''
    
    curr_weights = initial_weights
    
    for itern_num in range(max_iter):
        preds = inputs.dot(curr_weights)
        error = (preds - goal_preds) ** 2
        
        if np.average(error) < thresh:
            break
            
        delta = preds - goal_preds
        weight_deltas = np.outer(inputs,delta)
        curr_weights = curr_weights - (alpha*weight_deltas)
        if verbose:
            print(f'Error: {error}')
            print(f'Delta: {delta}')
            print(f'weight_deltas: {weight_deltas}')
            print(f'weights: {initial_weights}')
            print(f'curr_weights: {curr_weights}')
            
    # return weights from model after training
    return curr_weights,preds

In [75]:
inputs[0,:]

array([8.5 , 0.65, 1.2 ])

In [74]:
weights

array([[ 0.1,  0.1, -0.3],
       [ 0.1,  0.2,  0. ],
       [ 0. ,  1.3,  0.1]])

In [50]:
np.sum(inputs[0,:]*weights[0,:])

0.555

In [76]:
goal_preds[0,:]

array([0.1, 1. , 0.1])

In [89]:
new_weights,preds = grad_desc_generalized(inputs[0,:],transposed_weights,goal_preds[0,:],alpha=0.01,verbose=False)

In [90]:
preds

array([0.10013695, 0.99999398, 0.10026035])