# Chapter 3 Introduction to neural Prediciton

In [2]:
import numpy as np
import pandas as pd

In [1]:
def simple_neural_network(input, weight):
    prediction = input * weight
    return prediction

In [5]:
weight = 0.1
number_of_toes = [8.5,9.5,10,9]
input = number_of_toes[0]
pred = simple_neural_network(input,weight)
print(pred)

0.8500000000000001


In [35]:
def multi_input_nn(input_vector,weight_vector):
    pred_vector = input_vector * weight_vector
    pred = pred_vector.sum(axis=1)
    return pred

In [11]:
toes = np.array([8.5,9.5,9.9,9.0])
wlrec = np.array([0.65,0.8,0.8,0.9])
nfans = np.array([1.2,1.3,0.5,1.0])
weights = np.array([0.1,0.2,0])

In [12]:
weights.shape

(3,)

In [20]:
input_array = np.array([toes,wlrec,nfans]).transpose()

In [21]:
input_array.shape

(4, 3)

In [36]:
pred = multi_input_nn(input_array,weights)

In [37]:
pred

array([0.98, 1.11, 1.15, 1.08])

In [90]:
def mult_input_and_output_nn(inputs,weights):
    preds = np.dot(weights,inputs)
    return preds

In [ ]:
toes = np.array([8.5,9.5,9.9,9.0])
wlrec = np.array([0.65,0.8,0.8,0.9])
nfans = np.array([1.2,1.3,0.5,1.0])


In [40]:
weights = np.array([[0.1,0.1,-0.3],[0.1,0.2,0.0],[0.0,1.3,0.1]])

In [41]:
weights

array([[ 0.1,  0.1, -0.3],
       [ 0.1,  0.2,  0. ],
       [ 0. ,  1.3,  0.1]])

In [61]:
input_array[0,:]

array([8.5 , 0.65, 1.2 ])

In [80]:
input_array[0,:].shape

(3,)

In [87]:
input_array[0,:].reshape(1,3)

array([[8.5 , 0.65, 1.2 ]])

In [93]:
preds = mult_input_and_output_nn(input_array[0,:],weights)

In [94]:
preds

array([0.555, 0.98 , 0.965])

In [139]:
def multi_layer_nn(inputs,weights):
    #output of input layer feeds into hidden layer which feeds out to pred (output layer)
    hid = inputs.dot(weights[0])
    pred = hid.dot(weights[1])
    
    return pred

toes = np.array([8.5,9.5,9.9,9.0])
wlrec = np.array([0.65,0.8,0.8,0.9])
nfans = np.array([1.2,1.3,0.5,1.0])
input_array = np.array([toes,wlrec,nfans]).transpose()

ih_wgt = np.array([[0.1,0.2,-0.1],[-0.1,0.1,0.9],[0.1,0.4,0.1]]).T
hp_wgt = np.array([[0.3,1.1,-0.3],[0.1,0.2,0.0],[0.0,1.3,0.1]]).T
weights_multi = [ih_wgt,hp_wgt]

pred = multi_layer_nn(input_array[0,:],weights_multi)
print(pred)

[0.2135 0.145  0.5065]
